### POST - dodanie usera

POST https://instaapp-production-59d6.up.railway.app/api/user/register HTTP/1.1
content-type: application/json

{
        "userName": "aa",
        "name": "brek",
        "email": "ccc@dd.eee",
        "password": "Qwerty12",
        "passwordRepetation": "Qwerty12"
}

### POST - logowanie

POST https://instaapp-production-59d6.up.railway.app/api/user/login HTTP/1.1
content-type: application/json

{
        "login": "aa",
        "password": "Qwerty12"
}